### ISSUE TITLE
[Q] Is it wise to use "Aikar's Flags"?

### ISSUE THREAD

**Issue by ghost** [TheRemote/Legendary-Minecraft-Purpur-Geyser#1]
Hey man, and thanks for creating the image. It works wonderfully.

I was reading through PaperMC's documentation, and stumbled upon something named `Aikar's Flags`, which seems to be a collection of commandline flags to use when launching the java file.

I don't have much knowledge of Java in general, so maybe it's worthless/useless. In my case, I'm using a server with 128GB of RAM, so I have plenty of RAM to spare and to test out.

Is it worth looking into??

Link: [Aikar's Flags (Paper Docs)](https://docs.papermc.io/paper/aikars-flags) / [Aikar's Flags (Pufferfish Docs)](https://docs.pufferfish.host/optimization/how-to-apply-aikars-flags/)

**Comment by TheRemote** [comment]
Hey vp-en,

This does use some of the memory related ones but most of those flags are obsolete.  The JIT (just-in-time) compiler and garbage collection has been the default since OpenJDK 9 to give you an idea.  I was using all of these flags 5 years ago and they haven't changed very much.

If you happen to still be running Java 8 then this would enable some garbage collection options that speed things up.  If you don't have a server with more than at least 10 people on at a time then these won't make any difference.  If you have a huge server with like 30-40+ players then these could make a difference if you are having memory related problems / TPS issues.

I definitely wouldn't say they're worthless but I would say that we need to be talking about a minimum of probably a dozen players before the kind of things they are talking about in this writeup.  If this is the case though it's possible it's worth investigating.  This could be done by rebuilding the container with those options and comparing the differences on a very large server for example.  Hopefully that helps!

**Comment by ghost** [comment]
Thanks for the quick answer and clarification. I'll check it out and see if I notice any performance changes. I have a somewhat small-ish playerbase (10-20 players at most), so it might be redundant.
