### ISSUE TITLE
Why is this running as Root?!?

### ISSUE THREAD

**Issue by Wolfsbruder** [TheRemote/Legendary-Minecraft-Purpur-Geyser#9]
An image should never be running with root permissions (Minecraft doubly so)

What can be done to address this rather important security issue?

Perhaps like other docker images, the env variables UID and GID could be added as to who to run the image as.

This is an issue running this in docker on a NAS with other docker images. (it changes the permissions of all the other images and causes them to break as their own user can no longer write inside the image.

**Comment by TheRemote** [comment]
It's running inside a fake virtual machine.  That's how Docker works.  That's cute you think that the running user inside the container matters.

You also don't seem to understand the difference between a Docker volume and an image.  What the hell are you talking about it changes the permissions of all the other images?  That doesn't make sense.  

Are you sharing the volume with other images?  Because that is straight up user error and you don't have your terms straight.  A volume is not an image.  Root inside of a Docker container is not actually root on the system.  Wow.

My god, the environment variables are not even shared between containers.  They're completely isolated.  That is the POINT of Docker.

Closed.  Make a custom version if you want to mix volumes with other containers but that is honestly stupid and you should learn how to use Docker instead.  Highly amusing to be lectured by someone who doesn't understand the difference between an image and a volume about security. 

Do you understand that every cointainer has it's own isolated operating system it runs with?  This one uses Ubuntu.  Yes, you're running as the root user in a fake Ubuntu virtualized environment that only exists in memory.

Let me guess.  You saw the warning at startup that the server is running as root (yes, inside a completely isolated container).  You then assumed that I'm the moron and that it's not your configuration when you were having permissions issues.  Ask me how I guessed.  You're not the first only the others were more open to the idea that something is misconfigured and we were able to get theirs going (yes, on a NAS, and almost certainly the family of NAS that you are running).

I'm really not even interested in helping you fix your config.  We've fixed lots of other people's before but it's your shitty NAS hosting setup that requires some more advanced configuration which you honestly don't have a prayer of achieving on your own.

I'll give you a hint though.  You need to create a separate volume for the Minecraft container (duh).  That is the only thing that it will change permissions on.  If you're trying to use the same volume for multiple containers then yes it's going to clobber the permissions because you are using it wrong and have absolutely no clue what you're doing.  That's a HUGE security issue as well.  Keep them isolated  and separate (again, duh).

If you were half as smart as you think you are here you should now be putting 2+2 together and realizing that your existing setup is HORRIBLE for security.  

You're telling me you're sharing volumes between multiple containers and that they can all access the same volume files?  Wow.  That's user-erroring so hard that you've managed to make it *LESS* secure than standalone (because it is not designed to work that way nor will most containers be designed to work that way).  You've completely negated any advantage of using Docker at all in your quest to try to make it work like regular standalone Linux instead of just, well, Docker with completely isolated containers/volumes and nice things like that (the reason people use it?).  Incredible!

You'd be better off running the standalone version with your understanding of Docker.  There's no way that's happening though on some NAS setup which I'm sure you're well aware of.  Good luck, you're so smart I'm sure you'll recode the container or find some way to run it incorrectly the way you'd like.  Or you won't.  I don't care.

This was truly amazing to read after coming home from my work shift as an IT engineer.  Grade AAA user error and so cocksure that you know what you're doing.  That is unbelievable you're trying to share Docker VOLUMES between containers and are trying to lecture me about security.  Absolutely hilarious.  The whole point of Docker is to *isolate* all of it.  Not share.  

It's honestly rare to encounter users like you fortunately (most people want help and are open to the fact they don't know everything) but of the few I do encounter you're honestly all the same.  You'd never cut it in my industry and people like me would laugh you out of the room the second you try to blame this stuff on the engineers/developers/etc. when you don't have your terms and facts straight.

I'm only glad that here I can respond like this since I'm not at work anymore.  I have to be nicer to the customers even if they're being obnoxiously dumb (since they pay my salary) but I don't need to tolerate this here.  

How is it not your first thought that you may be missing something?  Even as an expert it's my first thought and I'd never be throwing out things like this.  The answer is simply that you are sharing volumes/paths which is completely inappropriate.  

Docker seems to be something you think of to just run stuff on your NAS.  You cannot seriously be running it for the security reasons you're trying to lecture me about here.  The whole set of Minecraft containers were actually developed as a result of the log4j hacks because even user isolation *wasn't enough* (which is what I refer to as standalone, even not running as a root user).  It needed even *more* protection thus Docker / containers.    

We needed to containerize the entire operating system and isolate it in it's own instance.  That means if your Minecraft server gets hacked they're just stuck inside a fake Ubuntu instance that only exists in RAM.  They only have access to the files inside the Docker volume which unless people are using it completely incorrectly like you would only be the Minecraft server files.  On your setup they'd have access to all of the files running in any container because you're sharing a volume and have broken their isolation.  

Root on that fake system is *not* root on your real system (again, the POINT of Docker!).  It's root inside your fake Ubuntu instance that no longer even exists the second the container stops.  A fresh copy is loaded from the original image and no changes are recorded (unless it's to the volume files).  That is why you need to keep the volume isolated from everything else as well!
